// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CampaignFormController from "./campaign_form_controller"
application.register("campaign-form", CampaignFormController)

import FormToggleController from "./form_toggle_controller"
application.register("form-toggle", FormToggleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)
